### ISSUE TITLE
Audiobook scanning error

### ISSUE THREAD

**Issue by powaypat** [DobyTang/LazyLibrarian#1207]
Hello,

I am running LL in a docker in unRaid and I keep getting this error when I am selecting 'Library Scan' under the Audiobook tab. Any ideas?

2018-01-27 20:37:03 | ERROR | AUDIO_SCAN | librarysync.py | LibraryScan | 949 | Unhandled exception in libraryScan: Traceback (most recent call last): File "/app/lazylibrarian/lazylibrarian/librarysync.py", line 570, in LibraryScan newauthor, authorid, new = addAuthorNameToDB(author) # get the author name as we know it... File "/app/lazylibrarian/lazylibrarian/importer.py", line 43, in addAuthorNameToDB author = formatAuthorName(author) File "/app/lazylibrarian/lazylibrarian/formatter.py", line 379, in formatAuthorName author = makeUnicode(author) File "/app/lazylibrarian/lazylibrarian/formatter.py", line 241, in makeUnicode txt = txt.decode(encoding) AttributeError: 'list' object has no attribute 'decode'
-- | -- | -- | -- | -- | -- | --
2018-01-27 20:37:03 | DEBUG | AUDIO_SCAN | librarysync.py | LibraryScan | 434 | [/books/Audiobooks] Now scanning subdirectory /Amanda Lindhout & Sara Corbett - A House in the Sky
2018-01-27 20:37:03 | INFO | AUDIO_SCAN | librarysync.py | LibraryScan | 311 | Scanning Audio directory: /books/Audiobooks

**Comment by philborman** [comment]
Interesting, seems the audiobook mp3 tag for "performer" or "composer" is returning us a list rather than a single string. didn't know that was possible. 
Can't tell whether it's performer or composer as we don't log enough info.
Is this a problem following a recent lazylibrarian upgrade (the id3 reader library changed recently) or is it just that we haven't scanned that book before?

**Comment by powaypat** [comment]
Thanks for the quick reply. I think I found the problem (I am on version 8f03b2). When I deleted the 'Artist' tag the scanner started to work, so I thought it's maybe a problem with the tags. I edit all my tags with mp3tag. Under the mp3tag settings, it is set to write ID3v2.3 UTF-16 when editing the tags. I changed it to write ID3v2.4 UTF-8 and now LL can scan them just fine.

**Comment by philborman** [comment]
Right, so it looks like the library might need changing/fixing
There are notes in the library code about working with v2.3 so that part should be ok, I guess it can't handle utf-16. Beyond my limited knowledge, but I will see if there is a simple alternative library we could use. At least you have a workaround for now.
